src/OnlineGroceryWebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LogoutView
from .views import home_page, about_page, contact_page
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
# from accounts.views import login_page, register_page, guest_register_view
from accounts.views import LoginView, RegisterView, guest_register_view

# from carts.views import cart_home

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', home_page, name='home'),
    #url(r'^$', 'src.OnlineGroceryWebsite.views.home_page', name='home'),
    # url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    # url(r'^login/$', login_page, name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    # url(r'^cart/$', cart_home, name='cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    # url(r'^register/$', register_page, name='register'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update,
        checkout_home,
        checkout_done_view,
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!-- jquery-confirm CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>




<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- Django Secure AJAX JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- OnlineGrocery custom js -->
<script src='{% static "js/onlinegrocerywebsite.js" %}'></script>

src/templates/base/navbar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'about' as about_url %}
{% url 'cart:home' as cart_url %}

<style>
a.normal {
  font-weight: normal;
}

a.light {
  font-weight: lighter;
}

a.thick {
  font-weight: bold;
}

a.thicker {
  font-weight: 900;
}
</style>

<link rel='stylesheet' type="image/png" href='{% static "css/favicon1.png" %}'>

<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm fixed-top">
    <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %}{{ brand_name }}{% else %}Alfamart Perpetual Biñan Online Store{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <!-- <div class="input-group p-0 justify-content-center">
            <form action="/search" method="get" class="w-100 m-0" style="padding-right: 20%;">
                <div class="input-group-append rounded-left">
                    <input type="text" class="form-control rounded-left form-control-sm" autocomplete="off" style="float: left; border-radius: 0;" name="q" placeholder="What you want...">
                    <button class="btn btn-success btn-sm rounded-right" style="border-radius: 0;" type="submit">Search</button>
                </div>
            </form>
        </div> -->
        {% include 'search/snippets/search-form.html' %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}"><a href="{{ home_url }}" class="nav-link thick"><span class=""></span> Home</a></li>
            
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}"><a href="{{ contact_url }}" class="nav-link thick"><span class=""></span>Contact</a></li>

            <li class="nav-item {% if request.path == product_list_url %}active{% endif %}"><a href="{{ product_list_url }}" class="nav-link thick"><span class=""></span> Products</a></li>
            <!-- <li class="nav-item {% if request.path == about_url %}active{% endif %}"><a href="{{ about_url }}" class="nav-link"><span class=""></span> About</a></li> -->
            
            {% if request.user.is_authenticated %}
            
            <!-- <li class="nav-item"><a href="/profile?user={{session.uid}}" class="nav-link"><span class=""></span>You</a>
            </li> -->
           <!--  <li class="nav-item"><a href="/out" class="nav-link"><span class=""></span> Logout</a></li> -->
           <li class="nav-item"><a href="#" class="nav-link thick"><span class=""></span> Account </a></li>
            <li class="nav-item {% if request.path == logout_url %}active{% endif %}"><a href="{{ logout_url }}" class="nav-link thick"><span class=""></span> Logout</a></li>
            {% else %}
            <li class="nav-item {% if request.path == register_url %}active{% endif %}"><a href="{{ register_url }}" class="nav-link thick"><span class=""></span> Signup</a></li>
            <li class="nav-item {% if request.path == login_url %}active{% endif %}"><a href="{{ login_url }}" class="nav-link thicker"><span class=""></span> Login</a></li>
            {% endif %}
            <div class="col-3">
            <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a href="{{ cart_url }}" class="nav-link"><span class='navbar-cart-count badge badge-primary'>{{request.session.cart_items}}</span><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
            </div>
        </ul>
    </div>
</nav>