src/OnlineGroceryWebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LogoutView
from .views import home_page, about_page, contact_page
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view
# from accounts.views import login_page, register_page, guest_register_view
from accounts.views import LoginView, RegisterView, guest_register_view

# from carts.views import cart_home

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', home_page, name='home'),
    #url(r'^$', 'src.OnlineGroceryWebsite.views.home_page', name='home'),
    # url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    # url(r'^login/$', login_page, name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    # url(r'^cart/$', cart_home, name='cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    # url(r'^register/$', register_page, name='register'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update,
        checkout_home,
        checkout_done_view,
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),
]

src/products/urls.py
from django.conf.urls import url

from .views import (
        # ProductListView, 
        # ProductDetailSlugView, 
        product_list_view,
		product_detail
        # product_list_view_last
        )

urlpatterns = [
    # url(r'^$', ProductListView.as_view(), name='list'),
    # url(r'^(?P<category_slug>[-\w]+)/$', product_list_view_last, name='product_list_by_category'),

    url(r'^$', product_list_view, name='list'),
    url(r'^(?P<category_slug>[-\w]+)/$', product_list_view, name='product_list_by_category'),
    # url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    # url(r'^(?P<id>\d+)/(?P<detail_slug>[-\w]+)/$', product_detail, name='detail'),
    url(r'^products/(?P<slug>[-\w]+)/$', product_detail.as_view(), name='detail'),


]

src/products/models.py
from django.db.models import Q
import random
import os
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from OnlineGroceryWebsite.utils import unique_slug_generator
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
#     print(instance)
#     print(filename)
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active = True)

    def featured(self):
        return self.filter(featured=True, active = True)

    def search(self, query):
        lookups = (Q(title__icontains=query) | 
        Q(description__icontains=query) |
        Q(price__icontains=query) |
        Q(tag__title__icontains=query))
        # return self.get_queryset().active().filter(lookups).distinct()
        # Q(tag__name__icontains=query)
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self): #Product.objects.featured()
        return self.get_queryset().featured()
        
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) #Product.objects == self.queryset()
        if qs.count() == 1:
            return qs.first()
        return None
    def search(self, query):
        lookups = Q(title__icontains=query) | Q(description=query)
        # return self.get_queryset().active().filter(lookups).distinct() #eto lang ung meron at wala ung productqueryset #orignal ito
        return self.get_queryset().active().search(query)



#category models
class Category(models.Model):
    title              = models.CharField(max_length=250)
    description        = models.CharField(max_length=250)
    slug               = models.SlugField(max_length=200, unique=True)
    active             = models.BooleanField(default=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    # def get_absolute_url(self):
    #     return reverse('products:postcategory', args=[self.slug])
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:product_list_by_category", args=[self.slug])



    
# Product
class Product(models.Model): #ProductCategory
    category        = models.ForeignKey(Category)
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20)
    image           = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured        = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    
    
    objects         = ProductManager()
    class Meta:
        ordering = ('title',)
        # ordering = ('-timestamp',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", args=[self.slug])

    @property
    def name(self):
        return self.title

def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

src/products/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

src/products/views.py
# from django.views import ListView
from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from carts.models import Cart
# from .forms import CartAddProductForm
from .models import Product, Category


# class ProductListView(ListView):
#     template_name = "products/list.html"


#     def get_queryset(self, *args, **kwargs):
#         request = self.request
#         return Product.objects.all()

#master-------------------------------------------------------------------------------------------------------

def product_list_view(request, category_slug=None):
    category = None
    categories = Category.objects.filter(active=True)
    products = Product.objects.filter(active=True)


    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    # queryset = Product.objects.all()
    # context = {
    #     'object_list': queryset
    # }
    # return render(request, "products/list.html", context)
    return render(request, 'products/list.html', {'category':category,
                                                  'categories':categories,
                                                  'products':products})



    
#-----------------------------------------------------------------------------------------------------------
# class ProductListView(ListView):
#     template_name = "products/list.html"

#     # def get_context_data(self, *args, **kwargs):
#     #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
#     #     print(context)
#     #     return context

#     def get_queryset(self, *args, **kwargs):
#         request = self.request
#         return Product.objects.all()


# def product_list_view(request):
#     queryset = Product.objects.all()
#     context = {
#         'object_list': queryset
#     }
#     return render(request, "products/list.html", context)

class product_detail(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(product_detail, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Uhhmmm ")
        return instance


def product_detail_view(request, pk=None, *args, **kwargs):
    instance = Product.objects.get_by_id(pk)
    if instance is None:
        raise Http404("Product doesn't exist")
    context = {
        'object': instance
    }
    return render(request, "products/detail.html", context)
#-----------------------------------------------------------------------------------------

# def product_detail(request, slug):
#     # context = super(product_detail, self).get_context_data(*args, **kwargs)
#     # cart_obj, new_obj = Cart.objects.new_or_get(self.request)
#     # context['cart'] = cart_obj

#     product = get_object_or_404(Product, slug=slug, active=True)
#     # cart_product_form = CartAddProductForm()
#     return render(request,
#                   'products/detail.html',
#                   {'product':product})

#-----------------------------------------------------------------------------------------

# def get_context_data(self, *args, **kwargs):
#         context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
#         cart_obj, new_obj = Cart.objects.new_or_get(self.request)
#         context['cart'] = cart_obj
#         return context


# def ProductDetailSlugView(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, active=True)
#     # cart_product_form = CartAddProductForm()
#     return render(request,
#                   'products/detail.html',
#                   {'product':product})

# class ProductDetailSlugView(DetailView):
#     queryset = Product.objects.all()
#     template_name = "products/detail.html"

#     def get_object(self, *args, **kwargs):
#         request = self.request
#         slug = self.kwargs.get('slug')
#         #instance = get_object_or_404(Product, slug=slug, active=True)
#         try:
#             instance = Product.objects.get(slug=slug, active=True)
#         except Product.DoesNotExist:
#             raise Http404("Not found..")
#         except Product.MultipleObjectsReturned:
#             qs = Product.objects.filter(slug=slug, active=True)
#             instance = qs.first()
#         except:
#             raise Http404("Uhhmmm ")
#         return instance



# class ProductDetailView(DetailView):
#     #queryset = Product.objects.all()
#     template_name = "products/detail.html"

#     def get_context_data(self, *args, **kwargs):
#         context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
#         print(context)
#         # context['abc'] = 123
#         return context

#     def get_object(self, *args, **kwargs):
#         request = self.request
#         pk = self.kwargs.get('pk')
#         instance = Product.objects.get_by_id(pk)
#         if instance is None:
#             raise Http404("Product doesn't exist")
#         return instance


# def product_detail_view(request, pk=None, *args, **kwargs):


#     instance = Product.objects.get_by_id(pk)
#     if instance is None:
#         raise Http404("Product doesn't exist")


#     context = {
#         'object': instance
#     }
#     return render(request, "products/detail.html", context)













#di na toh need
class ProductFeaturedListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()


class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()
    template_name = "products/featured-detail.html"

#di na toh need

src/products/templates/products/snippets/card.html
{% load static %}

<div class="card" style="width: 15rem;">
  {% if instance.image %}
    <a href="{{ instance.get_absolute_url }}">
      <img class="card-img-top" src="{{ instance.image.url }}" alt="{{ instance.title }} logo">
    </a>

    
    <div class="card-body">
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>

    <!-- <a href="#" class="btn btn-primary">Add to cart</a> -->



    <!-- Modal for details -->


    <!-- end modal for details -->



    </div> <!--end of card-body -->
    

  <div class="card-body">
    <h5 class="card-title">{{ instance.title|linebreaks|truncatewords:14 }}</h5>
    <p class="card-text">{{ instance.description|linebreaks|truncatewords:3}}</p>
    <p class="card-text">₱{{ instance.price}}</p>
    

    <!-- <a href="{% url 'products:detail' slug=instance.slug %}" class="btn btn-warning">URL shortcut</a> -->
    {% endif %} 
  </div>
</div>

src/products/templates/products/snippets/update-cart.html
<!-- justify-content-center -->
<div class="input-group p-0 ">
    <!-- <form action="{% url 'cart:update' %}" method="POST" class="w-100 m-0" style="padding-right: 20%;"> {% csrf_token %} -->
    <form class='form-product-ajax' action="{% url 'cart:update' %}" method="POST" data-endpoint='{% url "cart:update" %}'> {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
      <span class='submit-span'>
    {% if product in cart.products.all %}
        In cart <button type='submit' class='btn btn-link'>Remove?</button>
    {% else %}
        <button type='submit'  class='btn btn-success'>Add to cart</button>
    {% endif %}
    </span>
    </form>
</div>

src/products/templates/products/snippets/view-cart.html
{% load static %}
{% url 'products:detail' as detail_url %}


<!-- Button trigger modal -->
<button class = "btn btn-primary btn-lg" data-toggle = "modal" data-target = "#myModal">
   Modal Product View

</button>

<!-- Modal -->
<div class = "modal fade" id = "myModal" tabindex = "-1" role = "dialog" 
   aria-labelledby = "myModalLabel" aria-hidden = "true">

   <div class = "modal-dialog">
      <div class = "modal-content">
         
         <div class = "modal-header">
            <button type = "button" class = "close" data-dismiss = "modal" aria-hidden = "true">
                  &times;
            </button>
            
            <h4 class = "modal-title" id = "myModalLabel">
               This Modal title
            </h4>
         </div>
         
         <div class="modal-body">



         </div>
         
         <div class = "modal-footer">
            <button type = "button" class = "btn btn-default" data-dismiss = "modal">
               Close
            </button>
            
            <button type = "button" class = "btn btn-primary">
               Submit changes
            </button>
         </div>
         
      </div><!-- /.modal-content -->
      </form>
      
   </div><!-- /.modal-dialog -->
  
</div><!-- /.modal -->


{% load static %}



<!-- Yung card.html -->
<div class="card" style="width: 15rem;">
  {% if instance.image %}
    <a href="{{ instance.get_absolute_url }}">
      <img class="card-img-top" src="{{ instance.image.url }}" alt="{{ instance.title }} logo">
    </a>

    
    <div class="card-body">
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>
        {% include 'products/snippets/update-cart.html' with product=instance cart=cart %}
        {% include 'products/snippets/view-cart.html' with product=instance cart=cart %}
    <!-- <a href="#" class="btn btn-primary">Add to cart</a> -->



    <!-- Modal for details -->


    <!-- end modal for details -->



    </div> <!--end of card-body -->
    

  <div class="card-body">
    <h5 class="card-title">{{ instance.title|linebreaks|truncatewords:14 }}</h5>
    <p class="card-text">{{ instance.description|linebreaks|truncatewords:3}}</p>
    <p class="card-text">₱{{ instance.price}}</p>
    

    <!-- <a href="{% url 'products:detail' slug=instance.slug %}" class="btn btn-warning">URL shortcut</a> -->
    {% endif %} 
  </div>
</div>